# Site wide configuration
#theme: jekyll-theme-minimal
title: Yunqiang Li (李运强） 
locale: en_US
description: PhD candidate in Delft University of Technology
  
owner:
  name: Yunqiang Li
  bio: "PhD candidate in Delft University of Technology."
  email: y.li-19@tudelft.nl

theme: jekyll-theme-leap-day

#theme: jekyll-theme-cayman
